services:
  java-maven-app:
    image: docker2624/pipeline
    ports:
      - 8080:8080
  Postgres:
    image: Postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=my-pwd 
       







    