pipeline {
    agent any 
    
    stages {

        stage('build') { 
            steps {
                script{
                echo "build app"
                }
            }
        }

        stage('test') {
            
            steps {
                script{
                echo "test app"
                }
            }
        }
        stage('deploy') {
            steps {
                script {
                   echo 'deploying docker image to EC2...'
                   def dockerCmd = "docker run -p 3080:3080 -d docker2624/pipeline
                   sshagent(['ec2-server-key']) {    
                       sh "ssh -o StrictHostKeyChecking=no ubuntu@35.190.250.114 ${dockerCmd}"
                   }
                }
            }
        }
    }
}
